### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by yiqings** [DL-Circle/3D-DDPM#2]
@z0l00, we appreciate your paper [Three-Dimensional Medical Image Synthesis with Denoising Diffusion Probabilistic Models](https://openreview.net/forum?id=Oz7lKWVh45H) very much. But we would like to ask when will the code be released?

**Comment by z0l00** [comment]
Thank you @yiqings for your interest. We are currently working on the submission of journal paper using our code extension. We will release our code by the end of October. The old and new codes will then be available here.

**Comment by yiqings** [comment]
Thank you so much @z0l00 for the prompt response, and would be very glad to have the good news!

**Comment by hishamcholakkal** [comment]
@z0l00, any update on the code release?

**Comment by yiqings** [comment]
@z0l00 Hi, hope everything is doing well. 

I notice that It has been almost one month since the end of October. I am wondering if we will have some updates soon.

**Comment by jizhang02** [comment]
Hi,

I'm also interested in your method! Plz let us know if your code is pulicated.

Thanks,
Jing

**Comment by awais00012** [comment]
still, the code is pending?

**Comment by z0l00** [comment]
Apologies for the delayed response. We're grateful for everyone's interest in our work. Our code has now been released in our new repository, which you can visit at https://github.com/mobaidoctor/med-ddpm/. Please feel free to explore it. If you have any questions, do not hesitate to contact us. Thank you.
